### ISSUE TITLE
Run plantuml using different base url is not working

### ISSUE THREAD

**Issue by CarlitosDroid** [plantuml/plantuml-server#171]
I have tried to change the base url without any success. The same happens with PLANTUML_LIMIT_SIZE, when I generate an image the limit is not being respected.

plantuml-ax/Dockerfile:
```
FROM plantuml/plantuml-server:tomcat

ARG BASE_URL=plantuml
ENV PLANTUML_LIMIT_SIZE=100

EXPOSE 8080
```
docker-compose.yml
```
version: '3.3'

services:
  plantuml-server:
    build:
      context: ./plantuml-ax
    container_name: plantuml-server
    ports:
      - 8080:8080
```

This is working with this url: http://localhost:8080/ but not with http://localhost/plantuml

**Comment by sgilson** [comment]
The argument has to be available as the server image is built. When you reference `plantuml/plantuml-server:tomcat` in the compose file, you are bringing in an image that has already been built with no base url.

The solution is to use the build context of this repo instead of using a local Dockerfile.

I have not tested with tomcat, but this works fine for jetty:

``` yml
version: '3.3'
services:
  plantuml:
    build:
      context: https://github.com/plantuml/plantuml-server.git
      dockerfile: Dockerfile.jetty
      args:
        BASE_URL: plantuml
```
