### ISSUE TITLE
health check for plantuml-server

### ISSUE THREAD

**Issue by oholimoli** [plantuml/plantuml-server#220]
I have currently a problem with the startup procedure of my reverse proxy with plantuml in docker-compose and would like to add a health check to my plantuml service in docker-compose.

The restart problem happens when the server that is running docker or just the docker service restarts because of an update for example. In this case my combination of nginx reverse proxy with plantuml is not starting.

This will go on forever:
```
nginx:1.21.6-alpine            "/docker-entrypoint.…"   6 days ago     Restarting (1) 27 seconds ago  
```

It seems like somehow plantuml is not ready when nginx restarts (`depends_on` has no effect) and then the only thing that helps is to manually run the command `docker-compose down ... up -s`. I don't know why everything works when I run the command manually but not when docker restarts.

To solve this I would like to implement a health check as described in this example (I hope this will solve the startup problem):
https://medium.com/geekculture/how-to-successfully-implement-a-healthcheck-in-docker-compose-efced60bc08e 

What would be a good health check for plantuml-server?

```
services:
  
  nginx:
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    hostname: reverse
    image: nginx:1.21.6-alpine
    depends_on:
      plantuml:
        condition: service_healthy
    .
    .
    .

  plantuml:
    image: plantuml/plantuml-server:tomcat-v1.2021.10
    container_name: plantuml
    networks:
      - nginx-network
    
    # What would be a healtcheck for the plantuml-server?
    healthcheck:
      test: <need some good health check here :)>
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

```
