### ISSUE TITLE
Why doesn't my PLANTUML_CONFIG_FILE environment variable work in Docker?

### ISSUE THREAD

**Issue by cosmolin** [plantuml/plantuml-server#239]
My `docker-compose.yml` is written as follows:

```yaml
version: '3'
services:

  server:
    container_name: plantuml-server
    image: plantuml/plantuml-server
    ports:
      - 8090:8080
    volumes:
      - ./config.puml:/srv/config.puml
    environment:
      - PLANTUML_CONFIG_FILE=/srv/config.puml
```

My `config.puml` is written as follows:

```plantuml
skinparam defaultTextAlignment center
```

Is there anything wrong?
