### ISSUE TITLE
Nginx can not serve it on subdirectory well since jetty-v1.2023.5

### ISSUE THREAD

**Issue by zero00072** [plantuml/plantuml-server#277]
**Describe the bug**

I have installed PlantUML container version `jetty-v1.2023.1` and version `jetty-v1.2023.5` behind Nginx reverse proxy. PlantUML ver `jetty-v1.2023.5` can not inject my `Host` base url (with subdirectory) to HTML urls. So that the HTML page expect the base url reffer to a real root, and omit them. Then, all web resources and urls missed.

**To Reproduce**

1. Setting Nginx reverse proxy.
```
location /plantuml/ {
  rewrite /plantuml(.+) $1 break;

  proxy_set_header Host $http_host/plantuml;

  proxy_pass http://plantuml:8080;
  proxy_cache off;
}
```

1. `docker-compose up -d plantuml`
1. Visit the web which Nginx served. With url: `https://<domain_name>/plantuml/`.

**Expected behavior**

Work well like PlantUML container version `jetty-v1.2023.1`.

**Screenshots**

| `jetty-v1.2023.1` | `jetty-v1.2023.5` |
| --- | --- |
| ![jetty-v1.2023.1](https://user-images.githubusercontent.com/2072036/233622443-dd25ac68-3c00-448c-99ee-4e911550ece5.png) | ![jetty-v1.2023.5](https://user-images.githubusercontent.com/2072036/233622529-284858dc-680c-4b4e-9e71-7f8aaefc52b2.png) |

**Desktop:**

- OS
  -  Debian GNU/Linux |
- Browser
  - Mozilla Firefox
- Version
  - 112.0.1

**Comment by zero00072** [comment]
There are no more information at [dockerhub](https://hub.docker.com/r/plantuml/plantuml-server) to describe the [usage](https://github.com/plantuml/plantuml-server#change-base-url).

Just remove all:

```
location /plantuml/ {
  proxy_pass http://plantuml:8080;
  proxy_cache off;
}
```

And add variable:
```yaml
---
version: '3'
services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    restart: always
    environment:
      BASE_URL: plantuml
      PLANTUML_LIMIT_SIZE: 8192
...
```
